### ISSUE TITLE
Support Thunderlaser (Rudia boards)?

### ISSUE THREAD

**Issue by jnweiger** [wholder/LaserCut#1]
There is a new branch that adds support for a thunderlaser nova35 to Thomas Oster's LibLaserCut here:
https://github.com/fablabnbg/LibLaserCut/tree/thunderlaser (local testing; to be upstreamed)
What is the odds that this should work with your LaserCut tool too?

**Comment by wholder** [comment]
LaserCut only uses the portion of LibLaserCut that supports the Epilog Zing, as I own one as was able to test the code with it.  It should be possible to add support for other laser cutters supported by LibLaserCut , but I would need some way to test the code before I could spend time on supporting them.  However, the way each laser cutter is supported in LaserCut is fairly modular, so someone who has the proper laser cutter should be able to make the additions needed to add support for new ones using the ZingLaser class as a model.

The MIniLaser code is more generic and, with minor changes, should work with any GRBL-based laser cutter, as it simply uses a serial port to send commands to the laser cutters' GRBL controller.  The main thing needing change is the Dimension object that sets the working area (7 x 8 inches for the MIniLaser.)

**Comment by mohoxo** [comment]
Hello. Now I use Visicut to operate my laser. I used smoothieware on my motherboard. I used LASERWEB. This is a good software, but the raster processing is not as good as Visicut. I don't know if LaserCut can also support Visicut using SMOOTHIWARE motherboard. If it can be supported, Visicut will become very powerful!
