### ISSUE TITLE
Crashing issues

### ISSUE THREAD

**Issue by MicrotypeUK** [wholder/LaserCut#4]
Hi, I have managed to install and run Lasercut from the jar file but it crashes when trying to send gcode to my modified Cricut Mini. I get an error log each time. Any advice would be really helpful.
Steve

**Comment by wholder** [comment]
If you an supply a few more details I can see if I can assist:

1. What OS are you running?
2. What version of Java? (on command line type: java -version)
3. Run LaserCut from command line to display any exceptions reported when the crash happens and post the text here.

  jave -jar LaserCut.jar

Note: you'll first need to cd to directory where LaserCut.jar is located.

Wayne

**Comment by MicrotypeUK** [comment]
Hi Wayne
Many thanks for coming back.
Details as requested:

1.OS  Windows 10 Pro 20H2
2. java -version 1.8.0_281
3. A fatal error has been detected by the Java Runtime Environment:
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007110b5db,
pid=18120, tid=0x0000000000005750
# JRE version: Java(TM) SE Runtime Environment (8.0_281-b09) (build
1.8.0_281-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.281-b09 mixed mode
windows-amd64 compressed oops)
# Problematic frame:
# C  [jSSC-2.8_x86_64.dll+0xb5db]
# Failed to write core dump. Minidumps are not enabled by default on client
versions of Windows

I can run Lasercut from command prompt or directly. It runs both times, but
crashes out every time I send to cutter or select load/unload mat

Best regards

Steve

**Comment by wholder** [comment]
Hmm.. it looks like the crash is happening in JSSC, which is the Java library LaserCut uses to talk to serial devices, such as the modified Cricut Mini.  If you google "jSSC-2.8_x86_64.dll+0xb5db" you'll see that quite a few people are having this issue with various other applications.

It appears that there are now newer versions of JSSC (see https://github.com/java-native/jssc/releases), so I've updated LaserCut to use version 2.9.2.  Please download this new build and let me know if it resolves your issue.

BTW, If that doesn't work, the Arduino project uses it's own version of the JSSC library "jssc-2.8.0-arduino4", so we can try that, as well.

Wayne

**Comment by MicrotypeUK** [comment]
Hi Wayne
That did it! All working fine.
Thanks so much for your time.
All the best Steve

**Comment by wholder** [comment]
> That did it! All working fine.

Glad to hear it.  How is LaserCut working out for you?  I haven't worked on this project in some time, but feedback is always welcome.

**Comment by MicrotypeUK** [comment]
Hi Wayne

Lasercut is working fine, but I now have a fault on the cutter. Lasercut
will allow it to Load Mat but the cutter will not Unload Mat or respond to
G0 Y0 or -10 say. I may have to recheck all my wiring again.
Having Lasercut will be a godsend as I don't have to convert and send to
the cutter in separate programs.
Once I solve my fault I will be able to use it more thoroughly.
Best regards Steve

**Comment by wholder** [comment]
Yeah, the wiring can be a bit tricky.  I had trouble counting the pins correctly on the two ICs on the PCB.  Let me know if I can help in any way.  I've converted 2 Minis to use my version of Matt Williams' code.
